# Generated by Django 4.2 on 2023-04-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('topic', models.CharField(max_length=120, verbose_name='Тема квиза')),
                ('number_of_questions', models.IntegerField(verbose_name='Количество вопросов')),
                ('time', models.IntegerField(help_text='длительность в минутах', verbose_name='Время выполнения')),
                ('required_to_pass', models.IntegerField(help_text='верность в %', verbose_name='Процент прохождения')),
                ('difficulty', models.CharField(choices=[('легко', 'легко'), ('средне', 'средне'), ('тяжело', 'тяжело')], max_length=6, verbose_name='Сложность')),
            ],
            options={
                'verbose_name': 'Квиз',
                'verbose_name_plural': 'Квизы',
            },
        ),
    ]
