# Generated by Django 4.2 on 2023-05-05 20:00

from django.db import migrations, models
import quizes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.CharField(max_length=120, validators=[quizes.models.validate_topic], verbose_name='Тема квиза'),
        ),
    ]
