# Generated by Django 4.2 on 2023-05-05 20:14

from django.db import migrations, models
import quizes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_alter_quiz_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=120, validators=[quizes.models.validate_name], verbose_name='Название'),
        ),
    ]
